import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';
import { ENV } from './utils/env';

/**
 * playwright-bdd config: turns our Gherkin .feature files into real
 * Playwright test files it can run.
 * - features: where the .feature (Gherkin scenario) files live.
 * - steps: files to load step definitions from. Includes fixtures/**
 *   alongside steps/** so the generator also picks up the custom `test`
 *   (createBdd(test) usage and fixture types) that the step definitions
 *   depend on — not just the Given/When/Then calls themselves.
 * - outputDir: where the generated .spec.js files are written. Gitignored
 *   and fully regenerated by `npm run bddgen` — never edit by hand.
 * bddTestDir (the returned path) is used below as the "chromium" project's
 * testDir, so Playwright only picks up the *generated* tests, not the
 * source .feature/.steps.ts files directly.
 */
const storefrontBddTestDir = defineBddConfig({
  features: 'features/storefront/**/*.feature',
  steps: ['steps/storefront/**/*.ts', 'fixtures/storefront/**/*.ts'],
  outputDir: '.features-gen/storefront',
});

const apiBddTestDir = defineBddConfig({
  features: 'api/storefront/features/**/*.feature',
  steps: ['api/storefront/steps/**/*.ts', 'api/storefront/fixtures/**/*.ts'],
  outputDir: '.features-gen/api',
});

export default defineConfig({
  // Tests currently drive a single guest session against one local
  // Vendure dev server — running them in parallel workers risks
  // cross-test interference (e.g. shared cart state) and unnecessary load
  // on a dev server that isn't built for concurrent traffic. Revisit this
  // if/when tests get proper session isolation.
  fullyParallel: false,
  // Guards against `test.only` accidentally being left in and silently
  // skipping the rest of the suite once this runs in CI.
  forbidOnly: !!process.env.CI,
  // Retry failures in CI only — local runs should fail immediately so
  // flakiness is obvious while you're actively working on a test.
  retries: process.env.CI ? 2 : 0,
  // Always 1, including in CI: the self-hosted runner drives tests against
  // the same single local Vendure dev server as local runs (see the
  // fullyParallel note above) — CI isn't a separate, scaled environment
  // here, so the cross-test cart-interference risk applies there too.
  workers: 1,
  // 'html' -> the local report opened via `npm run report`.
  // 'github' -> annotates failures directly on the CI run/PR.
  reporter: [['html'], ['github']],

  use: {
    // Applies to the "chromium" (UI) project below — ENV.storefrontBaseUrl
    // is overridable via STOREFRONT_BASE_URL, see utils/env.ts.
    baseURL: ENV.storefrontBaseUrl,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      // BDD-generated UI scenarios (features/storefront/*.feature).
      name: 'chromium',
      testDir: storefrontBddTestDir,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      // Same storefront BDD scenarios exercised as mobile web. This is not
      // native app testing; it verifies the responsive Vendure storefront
      // in a Chromium-based mobile viewport with touch support.
      name: 'mobile-chrome',
      testDir: storefrontBddTestDir,
      use: {
        ...devices['Pixel 5'],
      },
    },
    {
      // BDD-generated Shop GraphQL API scenarios. No browser involved:
      // these use Playwright's built-in `request` fixture only.
      name: 'api',
      testDir: apiBddTestDir,
    },
  ],
});
