import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';
import { ENV } from './utils/env';

/**
 * playwright-bdd config: turns our Gherkin .feature files into real
 * Playwright test files it can run.
 * - features: where the .feature (Gherkin scenario) files live.
 * - steps: files to load step definitions from. Includes fixtures/**
 *   alongside steps/** so the generator also picks up the custom `test`
 *   (createBdd(test) usage and fixture types) that the step definitions
 *   depend on — not just the Given/When/Then calls themselves.
 * - outputDir: where the generated .spec.js files are written. Gitignored
 *   and fully regenerated by `npm run bddgen` — never edit by hand.
 * bddTestDir (the returned path) is used below as the "chromium" project's
 * testDir, so Playwright only picks up the *generated* tests, not the
 * source .feature/.steps.ts files directly.
 */
const bddTestDir = defineBddConfig({
  features: 'features/**/*.feature',

  steps: ['steps/**/*.ts', 'fixtures/**/*.ts'],

  outputDir: '.features-gen',
});

export default defineConfig({
  // Tests currently drive a single guest session against one local
  // Vendure dev server — running them in parallel workers risks
  // cross-test interference (e.g. shared cart state) and unnecessary load
  // on a dev server that isn't built for concurrent traffic. Revisit this
  // if/when tests get proper session isolation.
  fullyParallel: false,
  // Guards against `test.only` accidentally being left in and silently
  // skipping the rest of the suite once this runs in CI.
  forbidOnly: !!process.env.CI,
  // Retry failures in CI only — local runs should fail immediately so
  // flakiness is obvious while you're actively working on a test.
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : 1,
  // 'html' -> the local report opened via `npm run report`.
  // 'github' -> annotates failures directly on the CI run/PR.
  reporter: [['html'], ['github']],

  use: {
    // Applies to the "chromium" (UI) project below — ENV.storefrontBaseUrl
    // is overridable via STOREFRONT_BASE_URL, see utils/env.ts.
    baseURL: ENV.storefrontBaseUrl,
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  // Two independent projects, each scoped to its own testDir so they
  // don't accidentally pick up each other's files:
  projects: [
    {
      // BDD-generated UI scenarios (features/storefront/*.feature).
      name: 'chromium',
      testDir: bddTestDir,
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      // Plain Playwright API tests — no browser needed, so no `use`
      // device profile here (keeps these fast; see tests/api/storefront).
      name: 'api',
      testDir: './tests/api',
      testMatch: '**/*.spec.ts',
    },
  ],
});
